name: Build APKs and Publish Artifacts

on:
  push:
    branches: [ "dev", "master", "release/**" ]
    paths-ignore:
      - '**.md'
      - 'fastlane/**'
      - '.github/workflows/crowdin_contributors.yml'
  pull_request:
    branches: [ "dev" ]
    paths-ignore:
      - '**.md'
      - 'fastlane/**'
      - '.github/workflows/crowdin_contributors.yml'
  workflow_dispatch: { }

env:
  # Misc
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Build configuration
  BUILD_JAVA_VERSION: '17'
  BUILD_JAVA_DIST: 'adopt'

jobs:
  build_apk:
    strategy:
      matrix:
        build_type: ['debug', 'release']
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.BUILD_JAVA_VERSION }}
          distribution: ${{ env.BUILD_JAVA_DIST }}

      - name: Change Gradle wrapper permissions
        run: chmod +x ./gradlew

      - name: Restore Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Assemble ${{ matrix.build_type }} APK
        run: |
          build_type=${{ matrix.build_type }}
          ./gradlew :core:app:assemble${build_type^}

      - name: Copy ${{ matrix.build_type }} APK
        run: |
          cp core/app/build/outputs/apk/${{ matrix.build_type }}/app-*.apk ./

      - name: Upload arm64-v8a ${{ matrix.build_type }} APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-arm64-v8a-${{ matrix.build_type }}
          path: app-arm64-v8a-${{ matrix.build_type }}.apk

      - name: Upload armeabi-v7a ${{ matrix.build_type }} APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-armeabi-v7a-${{ matrix.build_type }}
          path: app-armeabi-v7a-${{ matrix.build_type }}.apk

      - name: Upload x86_64 ${{ matrix.build_type }} APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-x86_64-${{ matrix.build_type }}
          path: app-x86_64-${{ matrix.build_type }}.apk
